### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by vados60** [JakeWharton/retrofit2-kotlin-coroutines-adapter#10]
@JakeWharton 
Please advise how am I supposed to handle Network exceptions when request fails? ex internet is unavailable?

In this case API call instead of Deferred<?> returns nothing and chain breaks here.
`api.login(username, password).await() ` -- somewhere inside execution fails and in Logcat I see 
<-- HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "URL HERE": No address associated with hostname

`interface API {

    @GET("login")

    fun login(@Query("username") username: String, @Query("password") password: String): Deferred<Response<BaseNetResponse<LoginResponse>>>

}`

**Comment by zsmb13** [comment]
You can put a `try-catch` around this, as the adapter calls [Deferred.completeExceptionally](https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/blob/9362f505c7e7e6c5ab3113641de35fdff4dd583e/src/main/java/com/jakewharton/retrofit2/adapter/kotlin/coroutines/experimental/CoroutineCallAdapterFactory.kt#L97) when the request fails.

```kotlin
try {
    api.login(username, password).await()
} catch (e: IOException) {
    // handle exception
}
```

**Comment by JakeWharton** [comment]
Yep. What they said.

https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/blob/9362f505c7e7e6c5ab3113641de35fdff4dd583e/src/test/java/com/jakewharton/retrofit2/adapter/kotlin/coroutines/experimental/DeferredTest.kt#L72-L81
