### ISSUE TITLE
[Question] Retrieving Error response body

### ISSUE THREAD

**Issue by adnan-SM** [JakeWharton/retrofit2-kotlin-coroutines-adapter#14]
When a network error occurs, something like a HTTP 400 error. Is there any way to get access to the error response body ? I need access to the custom error msg being sent in the error body.

**Comment by adnan-SM** [comment]
Never mind, looking at the source helped. Thanks !

For all others : You can return the type Deferred<Response <T> > and get access to the response object.

**Comment by tententen2** [comment]
you can check exception type and get error body

if you don't want to use Deferred<Response>
