### ISSUE TITLE
Is Deferred<Unit> supported?

### ISSUE THREAD

**Issue by LouisCAD** [JakeWharton/retrofit2-kotlin-coroutines-adapter#2]
I recall a snippet of a `UnitConverterFactory` you posted in an issue. Is is needed to support `Deferred<Unit>` for 204 No Content or ignored body responses?

**Comment by JakeWharton** [comment]
Yes. This is only a call adapter. If you want a converter for `Unit` as a body type, you'll need to install one separately.

**Comment by LouisCAD** [comment]
@JakeWharton Could be nice to post the snippet in the README since it's likely to be needed by users of this library

**Comment by JakeWharton** [comment]
I don't think that statement is accurate. I've been using Retrofit in
Kotlin for 2 years on many projects and never needed it. Also its utility
is independent of your desire to use coroutines with Retrofit and so having
it here doesn't make it discoverable for those who aren't using coroutines.

**Comment by PaulWoitaschek** [comment]
I don't understand why this is not provided out of the box. Or am I misunderstanding something?
When I have a `POST` or `PATCH` isn't `Deferred<Unit>` always what I want to return here?
When using retrofit directly I use a `Call<Void>`

**Comment by JakeWharton** [comment]
This is an adapter which provides you `Deferred<T>`. If you want to use `Unit` for `T`, you want a converter.

**Comment by PaulWoitaschek** [comment]
And how is that possible? I try to write a moshi adapter like

```kotlin
class UnitJsonAdapter {

  @FromJson
  fun fromJson(value: String?): Unit = Unit

  @ToJson
  fun toJson(unit: Unit): String? = null
}
```

But it fails because the fromJson uses `void` in bytecode.

**Comment by JakeWharton** [comment]
https://github.com/square/retrofit/issues/2329#issuecomment-301316873

**Comment by PaulWoitaschek** [comment]
Thanks! Also I ask myself if there is no better representation for that. Like RxJava has `Completable`. Maybe just allow returning a plain `Job`?

**Comment by JakeWharton** [comment]
Can you file a new bug about that? Seems like it might work.

**Comment by PaulWoitaschek** [comment]
With that Unit call adapter I have exceptions for `Deferred<Unit>` (which are printed to std?)

```
W/System.err: kotlin.KotlinNullPointerException
W/System.err:     at com.jakewharton.retrofit2.adapter.kotlin.coroutines.experimental.CoroutineCallAdapterFactory$BodyCallAdapter$adapt$2.onResponse(CoroutineCallAdapterFactory.kt:102)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:123)
W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by LouisCAD** [comment]
@PaulWoitaschek Try adding the `UnitConverterFactory` before other converter factories when you configure your Retrofit.

**Comment by quentin41500** [comment]
I'm getting the same error @PaulWoitaschek, how did you fix it?

@LouisCAD, it is currently the first one on the list.

I'm just confused if I even still need the call adapter.

**Comment by PaulWoitaschek** [comment]
I fixed this by checking for the Unit type:

```kotlin
        override fun onResponse(call: Call<T>, response: Response<T>) {
          if (response.isSuccessful) {
            if (responseType == Unit::class.java) {
              @Suppress("UNCHECKED_CAST")
              deferred.complete(Unit as T)
            } else {
              deferred.complete(response.body()!!)
            }
          } else {
            deferred.completeExceptionally(HttpException(response))
          }
        }
```

@JakeWharton Will you accept a PR on this?

**Comment by ashdavies** [comment]
I'm getting the same error output as @PaulWoitaschek, with Retrofit 2.5.0, and including `UnitConverterFactory` before any others, using `Deferred<Response<Unit>>` alleviates it.

Is this still an issue? or is it just an incorrect configuration?

**Comment by roelvandun** [comment]
Also it would help debugging to write to `Log.e` instead of `Log.w`

**Comment by branoduris** [comment]
I'm getting the same error, with build in UnitResponseBodyConverter in Retrofit 2.6.0. I used @PaulWoitaschek fix on response function.
