### ISSUE TITLE
Compiled by a pre-release version

### ISSUE THREAD

**Issue by markchous** [JakeWharton/retrofit2-kotlin-coroutines-adapter#23]
Trying to use 1.3.0-rc-57, but I can't with the adapter. I am receiving the following error: ` Class 'com.jakewharton.retrofit2.adapter.kotlin.coroutines.CoroutineCallAdapterFactory' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler`

**Comment by JakeWharton** [comment]
You can suppress the warning. It should tell you how to higher up in the logs. Someone already sent #22 to update but I haven't had time to look at the error.

**Comment by markchous** [comment]
Awesome, thank you very much, Jake.
