### ISSUE TITLE
Gradle and Java 6?

### ISSUE THREAD

**Issue by grndvl1** [JakeWharton/retrofit2-kotlin-coroutines-adapter#26]
Why does the gradle script have java source at 
targetCompatibility = JavaVersion.VERSION_1_6
sourceCompatibility = JavaVersion.VERSION_1_6
Shouldn't we be using 8 now?

**Comment by JakeWharton** [comment]
There's no Java in the project anyway. Kotlin defaults to Java 6 as well. But you should be using Java 11 (or at least JDK 11) now.
