### ISSUE TITLE
[OPTIMIZE]Why no variables to store versions of core libraries?

### ISSUE THREAD

**Issue by XinyueZ** [JakeWharton/retrofit2-kotlin-coroutines-adapter#27]
Hi Jake,  take a look at https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/blob/master/build.gradle
why no variables to store versions of core libraries, any reasons?
for example:

`
api 'com.squareup.retrofit2:retrofit:2.4.0'
api 'org.jetbrains.kotlin:kotlin-stdlib:1.3.0-rc-57'
api 'org.jetbrains.kotlinx:kotlinx-coroutines-core:0.26.1-eap13'
`

 I have tried to do like this
https://github.com/XinyueZ/retrofit2-kotlin-coroutines-adapter/commit/b5477ff9663f6a32c5db8b540bcd961459d1d1b9

**Comment by JakeWharton** [comment]
This solves nothing and changes nothing.
