### ISSUE TITLE
Is the adapter working with Kotlin 1.3?

### ISSUE THREAD

**Issue by CapMontoro** [JakeWharton/retrofit2-kotlin-coroutines-adapter#35]
Just updated Android Studio today with new version of Kotlin. Coroutines are now stable.

For some reason my code stop working.

Could you confirm if an update is neccessary with the new import kotlinx.coroutines.* ?

**Comment by zsmb13** [comment]
The readme states that you need the non-experimental build of the library, which is this dependency:

```groovy
implementation 'com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2'
```

Seems to work for me with 1.3 stable.

**Comment by CapMontoro** [comment]
Fixed. Thank you.

**Comment by pdog18** [comment]
When I use `com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2` for `kotlin 1.3 `,but the library use kotlin-coroutines with `kotlinx.coroutines.experimental.Deferred` 。It does't work for me.

Any library use ` kotlinx.coroutines.Deferred` ？
