### ISSUE TITLE
Using `Deferred` type with `BehaviorDelegate`?

### ISSUE THREAD

**Issue by amiiy** [JakeWharton/retrofit2-kotlin-coroutines-adapter#40]
Hi! 
How can I use the `Deferred<User>` type  with `BehaviorDelegate`?  for example I can not run below code :
`delegate.returningResponse(response).getUser();`
`returningResponse(response)` actually returns User.

**Comment by amiiy** [comment]
sry. my bad.

**Comment by xxfast** [comment]
@amiiy were you able to use Deferred adapter with BehaviorDelegate?

**Comment by xxfast** [comment]
sry. my bad.

**Comment by xxfast** [comment]
For real though - for some reason  leaving `suspend` keyword on the function signature of the interface causes the delegate to see the return as Java::Object - instead of type deferred
