### ISSUE TITLE
Fire and forget

### ISSUE THREAD

**Issue by lanmonster** [JakeWharton/retrofit2-kotlin-coroutines-adapter#42]
I have a use case where I'm hitting a server, but I do not need the response at all. Is there a way to use coroutines to support this?

**Comment by JakeWharton** [comment]
You can specify the return type as `Void?` which will discard the response stream as soon as it's received and deliver a `null`. If you're just asking about firing off a coroutine and not caring about its result you can use `GlobalScope.launch` for that.
