### ISSUE TITLE
Could I cancel the request in an easy way like RxLifeCycle instead of cache the request in a collection?

### ISSUE THREAD

**Issue by zouzhenglu** [JakeWharton/retrofit2-kotlin-coroutines-adapter#6]
Could I cancel the request in an easy way like RxLifeCycle instead of cache the request in a collection?

**Comment by JakeWharton** [comment]
This is a general coroutine usage question and not specific to this library. Consider asking on StackOverflow or the Kotlin Slack coroutine channel.
